name: Vidaa Edge
description: Install custom Apps on Vidaa TVs
version: "1.0.1"
slug: vidaa-edge
url: "https://github.com/SeineEloquenz/ha-addons/tree/main/vidaa-edge"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8888/tcp: 443
options:
  jellyfin_url: "https://jellyfin.example.org"
schema:
  jellyfin_url: str
image: ghcr.io/seineeloquenz/{arch}-vidaa-edge
