name: "Vidaa Edge"
description: "Custom Apps for Vidaa TVs"
version: "1.0.0"
slug: "vidaa-edge"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  443/tcp: 443
options:
  jellyfin_url: "https://jellyfin.example.org
schema:
  jellyfin_url: str
image: "ghcr.io/SeineEloquenz/{arch}-vidaa-edge"
